.PHONY: clean All

All:
	@echo "----------Building project:[ Kiki-Météo - Debug ]----------"
	@cd "Kiki-Météo" && "$(MAKE)" -f  "Kiki-Météo.mk"
clean:
	@echo "----------Cleaning project:[ Kiki-Météo - Debug ]----------"
	@cd "Kiki-Météo" && "$(MAKE)" -f  "Kiki-Météo.mk" clean
